# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17HSar55LtGz57Iz_fSkcRJxV55RmmQfs
"""

import math as m

total = input("Enter three numbers (separted by space): ")
total = total.split()

a = float(total[0])
b = float(total[1])
c = float(total[2])

def formulaX(fNum, sNum, tNum):
  if fNum == 0:
    return "Vo Nghiem", "Unvalid"
  else:
    delta = (sNum**2) - (4*fNum*tNum)
    print(delta)
    if delta > 0:
      firstV = round((-sNum-delta**0.5)/(2*fNum),2)
      secV = round(((-sNum+delta**0.5)/(2*fNum)),2)
      return "Co 2 nghiem:", {firstV, secV}
    elif delta == 0:
      return "Co nghiem kep:", -sNum/(2*fNum)
    elif delta < 0:
      return "Vo nghiem", "Unvalid"

result, numbers = formulaX(a,b,c)
print(result,numbers)