# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pWQvfMzVicgxVlOGHCJ5AIno-2Hi0zjW
"""

# This is some python code made by VNA :D
import math as sans

x = 35
y = 0

def getODD(v):
  return (v%2 == 1)

def increaseX(value):
  global x
  x += value

def increaseY(valuee):
  global y
  y += valuee

for i in range(10):
  increaseX(i)
  if getODD(i):
    increaseY(round(i*sans.tan(i*192),3))

print(x,y)

myDomainRanking = [
    ["I stole the #0 spot"],
    ["Infinity Void", "Gojo Satoru"],
    ["Malevolent Shrine", "Ryomen Sukuna"],
    ["Yuji's Domain", "Yuji Itadori"],
    ["Yuka's Domain", "Okotsu Yuta"],
]

myDomainRanking.append(["Gambling Power","Hakari"])
# Nvm yuji's domain isn't confirmed
myDomainRanking.remove(myDomainRanking[3])

# Now we print the ranks
for i in myDomainRanking:
  indexer = myDomainRanking.index(i)
  if indexer == 0:
    continue
  print(f"#{indexer}: {i[0]} by {i[1]}!!")